name: Seu Nome de Fluxo de Trabalho

on:
  workflow_call:
    inputs:
      variavel-demo:
        description: 'Descrição da sua variável'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world! ${{ inputs.variavel-demo }}

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.